type: "object"
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
    description: Unique recipe ID.
  name:
    type: string
    description: Name of recipe.
  imageUrl:
    type: string
    description: URL for display image of recipe.
  category:
    type: array
    items:
      type: string
    description: List of categories this recipe belongs to.
  recipeUrl:
    type: string
    description: Direct URL to recipe. 